export const mockUser = {
  prenom: 'Marco',
  restaurant: 'La Trattoria',
  city: 'Marseille',
  plan: 'pro_annual',
}

export const mockIdeas = [
  {
    id: '1',
    hook: 'Ce que les touristes commandent vs les locaux',
    format: 'Vidéo courte',
    plateforme: 'TikTok',
    difficulte: 'Facile',
    brief: 'Filme toi en train de pointer sur deux colonnes au tableau. Côté gauche "touristes", côté droit "habitués". Révèle les différences avec humour.',
    legende: 'Touristes vs locaux 😂 Vous êtes dans quelle catégorie ? #marseille #restaurant #touristes',
  },
  {
    id: '2',
    hook: 'POV : t\'as essayé notre spécialité pour la première fois',
    format: 'Reel',
    plateforme: 'Instagram',
    difficulte: 'Facile',
    brief: 'Demande à un client de réagir en filmant son visage au moment de la première bouchée. Authentique, non scénarisé.',
    legende: 'Cette réaction dit tout 🤩 Première fois à La Trattoria et déjà conquis ! #foodreaction #marseille',
  },
  {
    id: '3',
    hook: '3 choses que tu ne savais pas sur notre pasta maison',
    format: 'Carrousel',
    plateforme: 'Instagram',
    difficulte: 'Moyen',
    brief: 'Crée un carrousel 3 slides : ingrédient secret / technique de fabrication / temps de préparation. Photos naturelles en cuisine.',
    legende: 'Notre pasta est faite maison chaque matin 🍝 Voici pourquoi elle est différente. #pastafaite #cuisineitalienne',
  },
  {
    id: '4',
    hook: 'Le plat qu\'on vend le plus et pourquoi',
    format: 'Vidéo courte',
    plateforme: 'TikTok',
    difficulte: 'Facile',
    brief: 'Annonce le plat bestseller, montre sa préparation en accéléré, révèle le prix. Fort potentiel viral.',
    legende: 'Notre plat numéro 1 depuis 3 ans... vous devinez lequel ? 👇 #bestof #restaurant #marseille',
  },
]

export const mockStats = {
  postsThisMonth: 12,
  totalViews: 8420,
  engagementRate: 4.2,
  bestDay: 'Vendredi',
  weeklyViews: [1200, 980, 1450, 1890, 2100, 1800, 2340],
  topPosts: [
    { type: 'Vidéo coulisses', plateforme: 'TikTok', vues: 2340, engagement: '6.1%' },
    { type: 'Plat du jour Reel', plateforme: 'Instagram', vues: 1890, engagement: '5.4%' },
    { type: 'Avis client', plateforme: 'Instagram', vues: 1450, engagement: '4.8%' },
  ],
}

export const mockTrends = [
  '#foodmarseille',
  '#cuisinelocale',
  '#plateaudujour',
  '#restomarseille',
  '#cheflife',
]

export const mockTrendingSounds = [
  {
    id: 's1',
    name: 'Oh No',
    artist: 'Kreepa',
    platform: 'TikTok',
    category: 'Tendance',
    uses: '2.4M',
    idea: 'Montre un plat raté vs le résultat final — transition au son',
    difficulty: 'Facile',
    trending: true,
  },
  {
    id: 's2',
    name: 'Aesthetic - Tollan Kim',
    artist: 'Tollan Kim',
    platform: 'Instagram',
    category: 'Ambiance',
    uses: '890K',
    idea: 'Montage slow-motion de tes plats avec lumière naturelle',
    difficulty: 'Facile',
    trending: true,
  },
  {
    id: 's3',
    name: 'Storytelling voiceover',
    artist: 'Original',
    platform: 'TikTok',
    category: 'Voiceover',
    uses: '1.8M',
    idea: 'Raconte l\'histoire de ton restaurant en 30s avec une voix off',
    difficulty: 'Moyen',
    trending: true,
  },
  {
    id: 's4',
    name: 'Montre ce que tu fais',
    artist: 'Trend FR',
    platform: 'TikTok',
    category: 'Tendance',
    uses: '5.1M',
    idea: 'Version restaurateur : "Montre ce que tu fais à 6h du matin" — prep cuisine',
    difficulty: 'Facile',
    trending: true,
  },
  {
    id: 's5',
    name: 'Chill Vibes',
    artist: 'Lo-Fi Beats',
    platform: 'Instagram',
    category: 'Ambiance',
    uses: '420K',
    idea: 'Timelapse de ta terrasse au coucher du soleil, ambiance relax',
    difficulty: 'Facile',
    trending: false,
  },
  {
    id: 's6',
    name: 'Before/After',
    artist: 'Trend',
    platform: 'TikTok',
    category: 'Transition',
    uses: '3.2M',
    idea: 'Ingrédients bruts → plat fini en une seule transition',
    difficulty: 'Moyen',
    trending: true,
  },
]

export const mockFormats = [
  {
    id: 'f1',
    name: 'POV Client',
    description: 'Filme du point de vue du client qui entre dans ton restaurant, s\'assoit, reçoit son plat.',
    platform: 'TikTok',
    avgViews: '15K-50K',
    difficulty: 'Facile',
    duration: '15-30s',
    tips: ['Utilise la caméra frontale', 'Montre la réaction au premier plat', 'Musique tendance en fond'],
  },
  {
    id: 'f2',
    name: 'Recipe Reel',
    description: 'Recette accélérée en 30 secondes. Vue plongeante, étapes claires, résultat final appétissant.',
    platform: 'Instagram',
    avgViews: '10K-30K',
    difficulty: 'Moyen',
    duration: '30-60s',
    tips: ['Lumière naturelle obligatoire', 'Texte overlay pour chaque étape', 'Musique lo-fi ou tendance'],
  },
  {
    id: 'f3',
    name: 'Day in the Life',
    description: 'Une journée type dans ton restaurant : de l\'ouverture à la fermeture.',
    platform: 'TikTok',
    avgViews: '20K-100K',
    difficulty: 'Moyen',
    duration: '30-60s',
    tips: ['Commence tôt le matin', 'Montre les coulisses brutes', 'Termine sur un plat servi au client'],
  },
  {
    id: 'f4',
    name: 'Avis Google mis en scène',
    description: 'Prends un vrai avis Google et mets-le en image avec le plat mentionné.',
    platform: 'Instagram',
    avgViews: '5K-15K',
    difficulty: 'Facile',
    duration: '15s',
    tips: ['Screenshot stylisé de l\'avis', 'Photo du plat mentionné', 'Remercie le client en légende'],
  },
]

export const mockSeasonalEvents = [
  { id: 'e1', name: 'Fête des Mères', date: '2026-05-31', idea: 'Menu spécial + story "Merci maman" avec photos de plats', daysUntil: 54 },
  { id: 'e2', name: 'Été / Terrasse', date: '2026-06-21', idea: 'Annonce l\'ouverture de ta terrasse avec un timelapse coucher de soleil', daysUntil: 75 },
  { id: 'e3', name: 'Fête de la Musique', date: '2026-06-21', idea: 'Si tu fais un événement, filme l\'ambiance + story interactive', daysUntil: 75 },
  { id: 'e4', name: 'Tour de France', date: '2026-07-04', idea: 'Menu "étape" thématique si le Tour passe dans ta ville', daysUntil: 88 },
]
